name: Add Entry

on:
  issues:
    types: [labeled]

concurrency:
  group: add-entry
  cancel-in-progress: false

jobs:
  add-entry:
    if: github.event.label.name == 'add-entry'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.0'
      - name: Build
        run: go build -o add_entry ./cmd/main.go
      - name: Run
        id: add_entry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LOG_PRIVATE_KEY: ${{ secrets.LOG_PRIVATE_KEY }}
          ISSUE_BODY: ${{ github.event.issue.body }}
        run: ./add_entry -owner ${{ github.repository_owner }} -repo ${{ github.event.repository.name }} -branch tlog -slog_level -4
      - name: Close Issue
        run: gh issue close ${{ github.event.issue.number }} --comment 'Auto-closed after adding to log. Index ${{ steps.add_entry.outputs.seq_index }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
